#+TITLE: Install Tips
#+AUTHOR: Junghanacs
#+LANGUAGE: ko

아! 패키징을 했으니 설치하면 된다고 생각하면
문제를 만난다.

* HOWTO BUILD EMACS

빌드 방법은 쉽다. 수백번도 더 해봤다. 근데 패키징은 다르다.

Emacs 패키지가 22.04 우분투에 수두룩 하다. 다 27.1 버전 관련 된 녀석들이다.
의존 관계로 연결되어 있는 터라. 괜히 패키징을 잘못했다가는 계속 딴소리가 나온다.
그래서 그냥 빌드하고 설치하는게 가장 속 편하다. 오래 걸리는 일도 아니고.
그러나 그렇게 해서는 사람들에게 편하게 다가가기 어렵다.

앱 설치 정도는 다들 하지 않나? 그렇게 되야 한다. 한번 설치하면 다른 녀석들하고
걸리지 않은다.

#+BEGIN_EXAMPLE
sudo apt show emacs-gtk
Package: emacs-gtk
Provides: editor, emacs, emacsen, info-browser, mail-reader, news-reader
Depends: emacs-bin-common (= 1:27.1+1-3ubuntu5), emacs-common (= 1:27.1+1-3ubuntu5), libacl1 (>= 2.2.23), libasound2 (>= 1.0.16), libc6 (>= 2.34), libcairo2 (>= 1.10.0), libdbus-1-3 (>= 1.9.14), libfontconfig1 (>= 2.12.6), libfreetype6 (>= 2.2.1), libgdk-pixbuf-2.0-0 (>= 2.22.0), libgif7 (>= 5.1), libglib2.0-0 (>= 2.37.3), libgmp10 (>= 2:6.2.1+dfsg), libgnutls30 (>= 3.7.2), libgpm2 (>= 1.20.7), libgtk-3-0 (>= 3.21.4), libharfbuzz0b (>= 0.9.42), libice6 (>= 1:1.0.0), libjansson4 (>= 2.7), libjpeg8 (>= 8c), liblcms2-2 (>= 2.2+git20110628), libm17n-0 (>= 1.6.1), libotf1 (>= 0.9.16), libpango-1.0-0 (>= 1.18.0), libpng16-16 (>= 1.6.2-1), librsvg2-2 (>= 2.32.0), libselinux1 (>= 3.1~), libsm6, libsystemd0, libtiff5 (>= 4.0.3), libtinfo6 (>= 6), libx11-6, libxext6, libxfixes3 (>= 1:4.0.1), libxml2 (>= 2.7.4), libxrender1, zlib1g (>= 1:1.1.4)
#+END_EXAMPLE

22.04 도 트리시터가 버전이 낮다. 그냥 도커 안에서 빌드하는게 좋겠다. 물론
따로 빌드도 해야겠다. 동작하려면 있어야 할 것 이다.

Package: libtree-sitter-dev
Version: 0.20.6-1~bpo22.04.1~ppa1

* Runtime Dependency
+ libtree-sitter 를 /usr/local/lib 복사.
  만들어 놓은 것은 제공하고 복사하는게 편하겠다. 패키지로 만들어도 되고.
  패키지로 만들려다가 손이 가니까 귀찮다. 중요하지 않다. 일단 패스.

  #+BEGIN_SRC sh :export code :tangle install-libtree-sitter.sh
    wget https://github.com/tree-sitter/tree-sitter/archive/v0.20.8.tar.gz \
    && tar xzf v0.20.8.tar.gz && cd tree-sitter-0.20.8 && make -j && sudo make install
  #+END_SRC

  #+BEGIN_EXAMPLE
  install -m755 libtree-sitter.a '/usr/local/lib'/libtree-sitter.a
  install -m755 libtree-sitter.so.0.0 '/usr/local/lib'/libtree-sitter.so.0.0
  ln -sf libtree-sitter.so.0.0 '/usr/local/lib'/libtree-sitter.so.0
  ln -sf libtree-sitter.so.0.0 '/usr/local/lib'/libtree-sitter.so
  #+END_EXAMPLE


* 아무튼 20.04
버전에 안정적으로 안착하기 위해서 패키지를 만들었다.
이 정도면 훌륭하다고 본다.

* DOCKER
How to docker isntall on ubuntu https://docs.docker.com/engine/install/ubuntu/

* BUILD
간단하게 하면 된다.

> sudo docker build --file ./build-docker/ubuntu-20.04/Dockerfile --tag emacs-gcc-29:git .
> sudo docker run --name emacs-gcc-29 emacs-gcc-29:git
> sudo docker cp emacs-gcc-29:/opt/deploy .

#+BEGIN_EXAMPLE
#!/usr/bin/env sh
# docker build -t konstare/emacs-gcc-pgtk:latest .
# id=$(docker create junghanacs/emacs-gcc-pgtk)
# docker cp $id:/opt/deploy .

sudo docker build --file ./build-docker/ubuntu-20.04/Dockerfile --tag emacs-gcc-29:git .
sudo docker run --name emacs-gcc-29 emacs-gcc-29:git
sudo docker cp emacs-gcc-29:/opt/deploy .

# 72M emacs-gcc-gtk_29.0.90.23.05.11.08.deb

# docker build --file build-docker/<distro path>/Dockerfile --tag kime-build:git .
# docker run --name kime kime-build:git
# docker cp kime:/opt/kime-out/kime.tar.xz .
# if you want to build deb package try this command instead
# docker cp kime:/opt/kime-out/kime_amd64.deb .

# How to docker isntall on ubuntu https://docs.docker.com/engine/install/ubuntu/
#+END_EXAMPLE

* REMOVE kelleyk-ubuntu-emacs
켈리의 우분투 버전을 설치한 경우
지워야 한다. 이게 아주 애를 먹인다. 깃헙에 가면 관련 이야기가 있는데
딱히 답이 없더라. 아래와 같이 하면 일단 지울 수 있다.

/etc 에서 ppa 를 지운다.
#+BEGIN_EXAMPLE
cd /etc/apt
cd trusted.gpg.d
sudo rm -Rf kelleyk-ubuntu-emacs.gpg*
#+END_EXAMPLE

apt remove 로 해봐야 안지워 진다.
아래와 같이 해서 강제로 지워야 한다. 문제있지만 지운다고 해야 지우는거다.
pkg: emacs28-nativecomp: 종속성 문제가 있지만 요청한대로 제거합니다:

#+BEGIN_EXAMPLE
 2176  cd /var/lib/dpkg/info
 2178  sudo mv emacs28-* /tmp
 2183  sudo dpkg --remove --force-remove-reinstreq --force-depends emacs28-common
 2184  sudo dpkg --remove --force-remove-reinstreq --force-depends emacs28-nativecomp
 2185  sudo dpkg --remove --force-remove-reinstreq --force-depends emacs28-el
#+END_EXAMPLE


* INSTALL my emacs deb

지우고 나니 설치가 한방에 된다. 설치하고 지금 사용 중이다. 똑같다.

#+BEGIN_EXAMPLE
  37   │ jhnuc➜  deb  ᐅ  sudo dpkg -i emacs29.deb
  38   │ [sudo] junghan 암호:
  39   │ (데이터베이스 읽는중 ...현재 765640개의 파일과 디렉터리가 설치되어 있습니다.)
  40   │ Preparing to unpack emacs29.deb ...
  41   │ Unpacking emacs-gcc-gtk (29.0.90.23.05.11.08) ...
  42   │ emacs-gcc-gtk (29.0.90.23.05.11.08) 설정하는 중입니다 ...
  43   │ Processing triggers for libc-bin (2.35-0ubuntu3.1) ...
  44   │ Processing triggers for man-db (2.10.2-1) ...
#+END_EXAMPLE

* STOW Install
[2023-05-11 Thu 21:36]
나는 개인적으로 빌드해서 stow 로 링크하는 게 좋더라.
근데 이렇게 패키징해서 밀어 버린터라. 어쩔 수 없게 되었다만.
가끔 도커로 패키징 할 생각이다.
